$schema: https://aka.ms/dsc/schemas/v3/bundled/config/document.json
resources:
  - name: Benchmark configuration
    type: Microsoft.Windows/WindowsPowerShell
    properties:
      resources:
        - name: Disable SSL 2.0
          type: SChannelDsc/Protocol
          properties:
            Protocol: "SSL 2.0"
            State: Disabled
        - name: Disable SSL 3.0
          type: SChannelDsc/Protocol
          properties:
            Protocol: "SSL 3.0"
            State: Disabled
        - name: Disable TLS 1.0
          type: SChannelDsc/Protocol
          properties:
            Protocol: "TLS 1.0"
            State: Disabled
        - name: Disable TLS 1.1
          type: SChannelDsc/Protocol
          properties:
            Protocol: "TLS 1.1"
            State: Disabled
        - name: Disable cipher NULL
          type: SChannelDsc/Cipher
          properties:
            Cipher: "NULL"
            State: Disabled
        - name: Disable cipher DES 56/56
          type: SChannelDsc/Cipher
          properties:
            Cipher: "DES 56/56"
            State: Disabled
        - name: Disable cipher Triple DES 168
          type: SChannelDsc/Cipher
          properties:
            Cipher: "Triple DES 168"
            State: Disabled
        - name: Disable cipher RC4 40/128
          type: SChannelDsc/Cipher
          properties:
            Cipher: "RC4 40/128"
            State: Disabled
        - name: Disable cipher RC4 56/128
          type: SChannelDsc/Cipher
          properties:
            Cipher: "RC4 56/128"
            State: Disabled
        - name: Disable cipher RC4 64/128
          type: SChannelDsc/Cipher
          properties:
            Cipher: "RC4 64/128"
            State: Disabled
        - name: Disable cipher RC4 128/128
          type: SChannelDsc/Cipher
          properties:
            Cipher: "RC4 128/128"
            State: Disabled
        - name: Disable cipher AES 128/128
          type: SChannelDsc/Cipher
          properties:
            Cipher: "AES 128/128"
            State: Disabled
        - name: Configure Cipher Suite ordering
          type: SChannelDsc/CipherSuites
          properties:
            IsSingleInstance: Yes
            # AES_128 and SHA256 are disabled
            CipherSuitesOrder:
              - TLS_AES_256_GCM_SHA384
              - TLS_AES_128_GCM_SHA256
              - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
              - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
              - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
              - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
              - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384
              - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
              - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
              - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
            Ensure: Present
